spring:
  application:
    name: parquimetro-api
  data:
    mongodb:
      uri: mongodb://mongodb:27017/parquimetrodb
  jackson:
    time-zone: America/Sao_Paulo
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html