version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/parquimetrodb
    depends_on:
      - mongodb
    networks:
      - parquimetro-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - parquimetro-network

volumes:
  mongodb_data:

networks:
  parquimetro-network:
    driver: bridge